/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package_Vistas;

import java.sql.Connection;
import java.util.Locale;
import package_Modelo.Conexion;

/**
 *
 * @author Santiago Lara
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VistaPrincipal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_alumno = new javax.swing.JMenu();
        menu_alumno = new javax.swing.JMenuItem();
        jMenu_materia = new javax.swing.JMenu();
        menu_materia = new javax.swing.JMenuItem();
        jMenu_admin = new javax.swing.JMenu();
        menu_inscripciones = new javax.swing.JMenuItem();
        menu_notas = new javax.swing.JMenuItem();
        jMenu_consultas = new javax.swing.JMenu();
        menu_consulta = new javax.swing.JMenuItem();
        jMenu_salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        jMenu_alumno.setText("Alumno");

        menu_alumno.setText("Formulario de Alumno");
        menu_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_alumnoActionPerformed(evt);
            }
        });
        jMenu_alumno.add(menu_alumno);

        jMenuBar1.add(jMenu_alumno);

        jMenu_materia.setText("Materia");

        menu_materia.setText("Formulario de Materia");
        menu_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_materiaActionPerformed(evt);
            }
        });
        jMenu_materia.add(menu_materia);

        jMenuBar1.add(jMenu_materia);

        jMenu_admin.setText("Administración");

        menu_inscripciones.setText("Manejo de Inscripciones");
        jMenu_admin.add(menu_inscripciones);

        menu_notas.setText("Manipulación de Notas");
        jMenu_admin.add(menu_notas);

        jMenuBar1.add(jMenu_admin);

        jMenu_consultas.setText("Consultas");

        menu_consulta.setText("Alumnos por Materias");
        menu_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consultaActionPerformed(evt);
            }
        });
        jMenu_consultas.add(menu_consulta);

        jMenuBar1.add(jMenu_consultas);

        jMenu_salir.setText("Salir");
        jMenuBar1.add(jMenu_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_alumnoActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        VistaAlumno vistaAlumno = new VistaAlumno();
        vistaAlumno.setVisible(true);
        jDesktopPane1.add(vistaAlumno);
    }//GEN-LAST:event_menu_alumnoActionPerformed

    private void menu_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_consultaActionPerformed

    private void menu_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_materiaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        VistaMateria vistaMateria= new VistaMateria();
        vistaMateria.setVisible(true);
        jDesktopPane1.add(vistaMateria);
    }//GEN-LAST:event_menu_materiaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
                Connection con = Conexion.getConexion();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_admin;
    private javax.swing.JMenu jMenu_alumno;
    private javax.swing.JMenu jMenu_consultas;
    private javax.swing.JMenu jMenu_materia;
    private javax.swing.JMenu jMenu_salir;
    private javax.swing.JMenuItem menu_alumno;
    private javax.swing.JMenuItem menu_consulta;
    private javax.swing.JMenuItem menu_inscripciones;
    private javax.swing.JMenuItem menu_materia;
    private javax.swing.JMenuItem menu_notas;
    // End of variables declaration//GEN-END:variables
}
