package package_Vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import package_Modelo.Alumno;
import package_Modelo.Inscripcion;
import package_Modelo.Materia;
import package_Persistencia.AlumnoData;
import package_Persistencia.InscripcionData;
import package_Persistencia.MateriaData;

/**
 *
 * @author Jon_kevin27
 */
public class VistaInscripcion extends javax.swing.JFrame {

    ArrayList<Materia> materias = new ArrayList();
    ArrayList<Alumno> alumnos = new ArrayList();
    private DefaultTableModel modelo = new DefaultTableModel();
    private MateriaData mData = new MateriaData();
    private AlumnoData aData = new AlumnoData();
    private InscripcionData inscData= new InscripcionData();

    /**
     * Creates new form VistaInscripcion
     */
    public VistaInscripcion() {
        initComponents();

        alumnos = (ArrayList<Alumno>) aData.mostrarAlumnos();
        modelo = new DefaultTableModel();
        cargarCbx();// carga los alumnos
        armarCabecera();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCbx_alumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jRbt_materiasinscriptas = new javax.swing.JRadioButton();
        jRbt_materiasnoinscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Materias = new javax.swing.JTable();
        jBt_inscribir = new javax.swing.JButton();
        jBt_anular = new javax.swing.JButton();
        jBt_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Formulario de Inscripción");

        jTextField1.setText("jTextField1");

        jLabel2.setText("Seleccione un alumno:");

        jCbx_alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_alumnosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Listado de Materias");

        jRbt_materiasinscriptas.setText("Materias Inscriptas");
        jRbt_materiasinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbt_materiasinscriptasActionPerformed(evt);
            }
        });

        jRbt_materiasnoinscriptas.setText("Materias no Inscriptas");
        jRbt_materiasnoinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbt_materiasnoinscriptasActionPerformed(evt);
            }
        });

        jTable_Materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable_Materias);

        jBt_inscribir.setText("Inscribir");
        jBt_inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_inscribirActionPerformed(evt);
            }
        });

        jBt_anular.setText("Anular Inscripción");
        jBt_anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_anularActionPerformed(evt);
            }
        });

        jBt_salir.setText("Salir");
        jBt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(196, 196, 196))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRbt_materiasinscriptas)
                                .addGap(74, 74, 74)
                                .addComponent(jRbt_materiasnoinscriptas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(88, 88, 88)
                                .addComponent(jCbx_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jBt_anular, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(67, 67, 67)
                                    .addComponent(jBt_salir))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jBt_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCbx_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbt_materiasinscriptas)
                    .addComponent(jRbt_materiasnoinscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBt_inscribir)
                    .addComponent(jBt_anular)
                    .addComponent(jBt_salir))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbx_alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_alumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbx_alumnosActionPerformed

    private void jRbt_materiasinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbt_materiasinscriptasActionPerformed
        borrarfilaTabla();
        jRbt_materiasnoinscriptas.setSelected(false);
        cargarMateriasInscriptas();
        jBt_inscribir.setEnabled(false);
        jBt_anular.setEnabled(true);
        
    }//GEN-LAST:event_jRbt_materiasinscriptasActionPerformed

    private void jRbt_materiasnoinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbt_materiasnoinscriptasActionPerformed
        borrarfilaTabla();
        jRbt_materiasinscriptas.setSelected(false);
        cargarMateriasNOInscriptas();
        jBt_inscribir.setEnabled(true);
        jBt_anular.setEnabled(false);
    }//GEN-LAST:event_jRbt_materiasnoinscriptasActionPerformed

    private void jBt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_salirActionPerformed
        dispose();
    }//GEN-LAST:event_jBt_salirActionPerformed

    private void jBt_inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_inscribirActionPerformed
       int filaSeleccionada = jTable_Materias.getSelectedRow();
        if (filaSeleccionada!=-1) {
            Alumno a=(Alumno)jCbx_alumnos.getSelectedItem();
            int idMateria=(Integer)modelo.getValueAt(filaSeleccionada, 0);
            String nombre= (String)modelo.getValueAt(filaSeleccionada, 1);
            int anioMateria= (Integer)modelo.getValueAt(filaSeleccionada, 2);
            Materia m= new Materia(idMateria, nombre, anioMateria,true);
            
            Inscripcion inscripcion= new Inscripcion (a, m,0);
            inscData.guardarInscripcion(inscripcion);
            borrarfilaTabla();
        }
    }//GEN-LAST:event_jBt_inscribirActionPerformed

    private void jBt_anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_anularActionPerformed
        int filaSeleccionada = jTable_Materias.getSelectedRow();
        if (filaSeleccionada!=-1) {
            Alumno a=(Alumno)jCbx_alumnos.getSelectedItem();
            int idMateria=(Integer)modelo.getValueAt(filaSeleccionada, 0);
            inscData.borrarInscripcion(a.getIdAlumno(),idMateria);
            borrarfilaTabla();
        } else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla.");
        }
    }//GEN-LAST:event_jBt_anularActionPerformed

    private void armarCabecera() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Año");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        jTable_Materias.setModel(modelo);
    }

    private void borrarfilaTabla() {
        int indice = modelo.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void cargarMateriasInscriptas() {
        Alumno selec = (Alumno) jCbx_alumnos.getSelectedItem();
        materias = (ArrayList) inscData.obtenerMateriasCursadas(selec.getIdAlumno());
        for (Materia m : materias) {
            modelo.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAnioMateria()});
        }
    }

    private void cargarMateriasNOInscriptas() {
        Alumno selec = (Alumno) jCbx_alumnos.getSelectedItem();
        materias = (ArrayList) inscData.obtenerMateriasNOCursadas(selec.getIdAlumno());
        for (Materia m : materias) {
            modelo.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAnioMateria()});
        }
    }

    public void cargarCbx() {
        for (Alumno alumno : alumnos) {
            jCbx_alumnos.addItem(alumno);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt_anular;
    private javax.swing.JButton jBt_inscribir;
    private javax.swing.JButton jBt_salir;
    private javax.swing.JComboBox<Alumno> jCbx_alumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRbt_materiasinscriptas;
    private javax.swing.JRadioButton jRbt_materiasnoinscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Materias;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
