package package_Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import package_Modelo.Conexion;
import package_Modelo.Materia;
import package_Persistencia.MateriaData;

/**
 *
 * @author Jon_kevin27
 */
public class VistaMateria extends javax.swing.JInternalFrame {

    private MateriaData matData = new MateriaData();
    private Materia materiaActual = null;
    

    /**
     * Creates new form VistaMateria
     */
    public VistaMateria() {
        initComponents();

        jT_codigo1.setEnabled(true);
        jT_nombre.setEnabled(false);
        jT_año.setEnabled(false);
        jRbt_estado.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jT_nombre = new javax.swing.JTextField();
        jT_codigo1 = new javax.swing.JTextField();
        jT_año = new javax.swing.JTextField();
        jBt_Nuevo = new javax.swing.JButton();
        jBt_Buscar = new javax.swing.JButton();
        jBt_Guardar = new javax.swing.JButton();
        jBt_Eliminar = new javax.swing.JButton();
        jBt_Salir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRbt_estado = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Materia");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Año:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Estado:");

        jT_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_nombreActionPerformed(evt);
            }
        });

        jT_codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_codigo1ActionPerformed(evt);
            }
        });

        jT_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_añoActionPerformed(evt);
            }
        });

        jBt_Nuevo.setText("Nuevo");
        jBt_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_NuevoActionPerformed(evt);
            }
        });

        jBt_Buscar.setText("Buscar");
        jBt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_BuscarActionPerformed(evt);
            }
        });

        jBt_Guardar.setText("Guardar");
        jBt_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_GuardarActionPerformed(evt);
            }
        });

        jBt_Eliminar.setText("Eliminar");
        jBt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_EliminarActionPerformed(evt);
            }
        });

        jBt_Salir.setText("Salir");
        jBt_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_SalirActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT_año, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jT_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jBt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRbt_estado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBt_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jBt_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBt_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jBt_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jT_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt_Buscar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRbt_estado))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBt_Nuevo)
                    .addComponent(jBt_Guardar)
                    .addComponent(jBt_Eliminar)
                    .addComponent(jBt_Salir))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_nombreActionPerformed

    private void jT_codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_codigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_codigo1ActionPerformed

    private void jT_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_añoActionPerformed

    private void jBt_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_GuardarActionPerformed

        try {
            Integer idMateria = Integer.valueOf(jT_codigo1.getText());
            String nombre = jT_nombre.getText();
            Integer año = Integer.valueOf(jT_año.getText());
            boolean estado= jRbt_estado.isSelected();
            
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No debe haber campos vacíos");
                return;
            }else {
                if (materiaActual== null) {
                Materia mate = new Materia(nombre, año, estado);
                    matData.guardarMateria(mate);
                }else {
                    Materia mate = new Materia(idMateria, nombre, año, estado);
                    matData.modificarMateria(mate);
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número válido");
        }
        limpiarCampos();
        
    }//GEN-LAST:event_jBt_GuardarActionPerformed

    private void jBt_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_NuevoActionPerformed
        jT_codigo1.setEnabled(true);
        jT_nombre.setEnabled(true);
        jT_año.setEnabled(true);
        jRbt_estado.setEnabled(true);
        limpiarCampos();
        System.out.println(materiaActual);
    }//GEN-LAST:event_jBt_NuevoActionPerformed

    private void jBt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_BuscarActionPerformed
        try {
            Integer idMateria = Integer.valueOf(jT_codigo1.getText());
            materiaActual = matData.buscarMateria(idMateria);
            if (materiaActual != null) {
                jT_nombre.setText(materiaActual.getNombre());
                jT_año.setText(String.valueOf(materiaActual.getAnioMateria()));
                jRbt_estado.setSelected(materiaActual.isActivo());
            System.out.println(materiaActual);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un código válido");
        }
    }//GEN-LAST:event_jBt_BuscarActionPerformed

    private void jBt_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_SalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBt_SalirActionPerformed

    private void jBt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_EliminarActionPerformed
         if (materiaActual != null) {
            matData.eliminarMateria(materiaActual.getIdMateria());
            materiaActual = null;
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(this, "No hay una materia seleccionada");

        }
    }//GEN-LAST:event_jBt_EliminarActionPerformed

    private void limpiarCampos() {
        jT_codigo1.setText("");
        jT_nombre.setText("");
        jT_año.setText("");
        jRbt_estado.setSelected(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt_Buscar;
    private javax.swing.JButton jBt_Eliminar;
    private javax.swing.JButton jBt_Guardar;
    private javax.swing.JButton jBt_Nuevo;
    private javax.swing.JButton jBt_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRbt_estado;
    private javax.swing.JTextField jT_año;
    private javax.swing.JTextField jT_codigo1;
    private javax.swing.JTextField jT_nombre;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
